### ISSUE TITLE
sshexec goal ignores sshExecutable setting in settings.xml

### ISSUE THREAD

**Issue by barrymw** [mojohaus/wagon-maven-plugin#11]
On windows, using the sshexec goal results in failure as the plugin wants to use the ssh command even though sshExecutable has been configured.

Stacktrace snippet:
org.apache.maven.wagon.providers.ssh.external.**ScpExternalWagon**.executeCommand(ScpExternalWagon.java:197)
	... 24 more
**Caused by: java.io.IOException: Cannot run program "ssh": CreateProcess error=2, The system cannot find the file specified**

server section in Settings.xml:

		<server>
			<id>vagrantbox</id>
			<username>webservd</username>
			<configuration>
                <scpExecutable>pscp</scpExecutable>
                <sshExecutable>plink</sshExecutable>
			</configuration>
		</server>

pom.xml:
extensions:

		<extensions>
			
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh-external</artifactId>
				<version>2.12</version>
			</extension>
		</extensions>

sshexec goal:

		<plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>wagon-maven-plugin</artifactId>
			<version>1.0</version>
			<executions>
				<execution>
					<id>execute-test-commands</id>
					<phase>deploy</phase>
					<goals>
						<goal>sshexec</goal>
					</goals>
					<configuration>
						<serverId>vagrantbox</serverId>
						<url>scpexe://host/var/apache2/vagrant/chimp-platform</url>
						<commands>
							<command>/var/apache2/vagrant/chimp-platform/create-vagrant-metadata.sh</command>
						</commands>
					</configuration>
				</execution>
			</executions>
		</plugin>

debug output for command:
`    [DEBUG] -- end configuration --
    scpexe://host/var/apache2/vagrant/chimp-platform - Session: Opened  
    Executing command: cmd.exe /X /C "ssh -i C:\Users\abc\.ssh\id_rsa -o "BatchMode yes"     webservd@host /var/apache2/vagrant/chimp-platform/create-vagrant-metadata.sh"
    scpexe://host/var/apache2/vagrant/chimp-platform - Session: Disconnecting  
    scpexe://host/var/apache2/vagrant/chimp-platform - Session: Disconnected`

Stacktrace:
[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:sshexec (execute-test-commands) on project eclipse-ide: Unable to execute remote command: Error executing command line: Error while executing process. Cannot run program "ssh": CreateProcess error=2, The system cannot find the file specified -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0:sshexec (execute-test-commands) on project eclipse-ide: Unable to execute remote command
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to execute remote command
	at org.codehaus.mojo.wagon.SshExecMojo.execute(SshExecMojo.java:81)
	at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingleWagonMojo.java:64)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.apache.maven.wagon.CommandExecutionException: Error executing command line
	at **org.apache.maven.wagon.providers.ssh.external.ScpExternalWagon.executeCommand**(ScpExternalWagon.java:214)
	at org.codehaus.mojo.wagon.SshExecMojo.execute(SshExecMojo.java:69)
	... 23 more
Caused by: org.codehaus.plexus.util.cli.CommandLineException: Error while executing process.
	at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:675)
	at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLineAsCallable(CommandLineUtils.java:134)
	at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:105)
	at org.codehaus.plexus.util.cli.CommandLineUtils.executeCommandLine(CommandLineUtils.java:74)
	at org.apache.maven.wagon.providers.ssh.external.ScpExternalWagon.executeCommand(ScpExternalWagon.java:197)
	... 24 more
**Caused by: java.io.IOException: Cannot run program "ssh": CreateProcess error=2, The system cannot find the file specified**
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.codehaus.plexus.util.cli.Commandline.execute(Commandline.java:655)
	... 28 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 30 more

**Comment by dantran** [comment]
looks like ssh executable is not on your path

**Comment by barrymw** [comment]
It's meant to be using plink as it's using the ssh-external extension and the sshExecutable config is set.

**Comment by barrymw** [comment]
@dantran, can you review [pull request 12](https://github.com/mojohaus/wagon-maven-plugin/pull/12) to make this plug in work on **Windows**.

````
Caused by: java.lang.ClassCastException: org.apache.maven.wagon.providers.ssh.external.ScpExternalWagon cannot be cast to org.apache.maven.wagon.providers.ssh.jsch.ScpWagon
   at org.codehaus.mojo.wagon.SshExecMojo.execute(SshExecMojo.java:69)
   at org.codehaus.mojo.wagon.AbstractSingleWagonMojo.execute(AbstractSingleWagonMojo.java:64)
   at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
   ... 21 more
````
